apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: arm64v8/nginx
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 10 # Start with 10% of traffic
        - pause: {duration: 60s} # Pause for 10 seconds after each step
        - setWeight: 50 # Increase to 50%
        - pause: {duration: 60s} # Pause again
        - setWeight: 100 # Finalize to 100%
