apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: arm64v8/nginx
        ports:
        - containerPort: 80
  strategy:
    canary:
      steps:
        - setWeight: 20
      	- pause: {}
      	- setWeight: 40
      	- pause: {duration: 30}
      	- setWeight: 60
      	- pause: {duration: 30}
      	- setWeight: 80
      	- pause: {duration: 30}
